//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myStorefront.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> ShippingAddressID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Subtotal { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<System.DateTime> dtCompleted { get; set; }
        public Nullable<System.DateTime> dtShipped { get; set; }
        public decimal ShippingCost { get; set; }
        public string Status { get; set; }
    
        public virtual Address ShippingAddress { get; set; }
        public virtual Address BillingAddress { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
