//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myStorefront.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int PaymentID { get; set; }
        public string CCNumber { get; set; }
        public int CCVC { get; set; }
        public string CCExpiryMonth { get; set; }
        public string CCExpiry { get; set; }
        public string Name { get; set; }
        public string Confirmation { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
